# Generated by Django 5.2.7 on 2025-11-26 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buildingdooraction',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.building'),
        ),
        migrations.AddField(
            model_name='buildingdooraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buildingdoors',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.building'),
        ),
        migrations.AddField(
            model_name='buildingdooraction',
            name='door',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.buildingdoors'),
        ),
    ]
